"""Initial migration

Revision ID: 4086b4204091
Revises: 
Create Date: 2025-02-27 04:14:07.588271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4086b4204091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_index(op.f('ix_datasets_metadata_dataset_id'), 'datasets_metadata', ['dataset_id'], unique=False)
    op.alter_column('patients', 'ext_patient_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'public_patient_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_patients_project_id'), 'patients', ['project_id'], unique=False)
    op.create_index(op.f('ix_patients_metadata_patient_id'), 'patients_metadata', ['patient_id'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_raw_files_dataset_id'), 'raw_files', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_raw_files_metadata_raw_file_id'), 'raw_files_metadata', ['raw_file_id'], unique=False)
    op.alter_column('samples', 'ext_sample_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_samples_patient_id'), 'samples', ['patient_id'], unique=False)
    op.create_index(op.f('ix_samples_metadata_sample_id'), 'samples_metadata', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_metadata_sample_id'), table_name='samples_metadata')
    op.drop_index(op.f('ix_samples_patient_id'), table_name='samples')
    op.alter_column('samples', 'ext_sample_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_raw_files_metadata_raw_file_id'), table_name='raw_files_metadata')
    op.drop_index(op.f('ix_raw_files_dataset_id'), table_name='raw_files')
    op.alter_column('projects', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_patients_metadata_patient_id'), table_name='patients_metadata')
    op.drop_index(op.f('ix_patients_project_id'), table_name='patients')
    op.alter_column('patients', 'public_patient_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'ext_patient_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_datasets_metadata_dataset_id'), table_name='datasets_metadata')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    # ### end Alembic commands ###
